caching:
  spring:
    ttl: 60000

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/crypto-prices
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: rooT2023
#  jpa:
#    hibernate.ddl-auto: update
#    generate-ddl: false
#    show-sql: false
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect